# Generated by Django 4.2.4 on 2024-05-25 13:35

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=50, verbose_name='Статус заявки')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('activated', models.DateTimeField(null=True, verbose_name='Дата активации заявки')),
                ('completed', models.DateTimeField(null=True, verbose_name='Дата завершения заявки')),
                ('creator_id', models.IntegerField(null=True, verbose_name='Создатель заявки')),
                ('moderator_id', models.IntegerField(null=True, verbose_name='Модератор услуг')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(max_length=255, verbose_name='Описание услуги')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото услуги')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена услуги')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', stocks.models.NewUserManager()),
            ],
        ),
    ]
