# Generated by Django 4.2.4 on 2024-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service', to='stocks.service'),
        ),
    ]
